### ISSUE TITLE
In iql.py, the target network doesn't appear to be updated during the config.n_jitted_updates updates

### ISSUE THREAD

**Issue by ShirongLiu** [nissymori/JAX-CORL#73]
In line 296, `return agent._replace(target_critic=new_target_critic)` 

should be put into the for loop `for _ in range(config.n_jitted_updates):` in line 283?

**Comment by nissymori** [comment]
@ShirongLiu Thank you for pointing out! Yes, you are right...! I will fix it!

**Comment by nissymori** [comment]
Hi! I rerun experiment and updated the report #75

**Comment by ShirongLiu** [comment]
Thanks for your work!
